### ISSUE TITLE
Wide-char can't process correctly

### ISSUE THREAD

**Issue by slzKud** [Wilenty/7zOverlay#1]
Thanks your project!
In the example,You use the char* to process ,but it can't process wide-char,such as chinese(你好,Hello) or japanese.if 7z filename include this,the program can't process and show an error.
However,it can use some way to avoid this.But i think you can fix it if you have time. For example,Use wchar or BSTR to replace char*.
It's my suggestion.That's all.

**Comment by slzKud** [comment]
By the way,if the dll path include wide-char,the program cannot process and show error 2.

**Comment by Wilenty** [comment]
Hello,
thanks for the suggestion! I will check it and will let you know, it may take a while...

In general I created this dll to use it in Inno Setup, because there's no good external 7-zip dll for it. But, Inno Setup does not support the PWideChar. So, I need to check how to solve it.

Best regards,
Wilenty

**Comment by Wilenty** [comment]
Sorry for many responses, but my internet connection has hangs-up and I didn't noticed it.

**Comment by slzKud** [comment]
it doesn't matter.

**Comment by Wilenty** [comment]
Hello,
I divided it for two functions, so now you can use ANSI or UNICODE characters.

Can you check this pre-release and let me know?

**Comment by slzKud** [comment]
yes,i can try it.thank you!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by slzKud** [comment]
i test the vb6 simple program,the dll works perfect.it can process the wide-char pefectly.
example: i use ‘x “D:\测试.7z" -od:\测试123",it can show succes。And extrace 7z file into correct folder.
it's awsome,Thank You and Your Project.i think it solved.
![QQ截图20200825214517](https://user-images.githubusercontent.com/23147878/91182421-bcbfac00-e71c-11ea-8b08-b6edd66aa676.png)

**Comment by Wilenty** [comment]
Thank you too for reporting and testing. 👍

**Comment by slzKud** [comment]
Sorry.it has a problem.
if the dll path include wide-char,the program cannot process and show error 2. 
Like this 
![图片](https://user-images.githubusercontent.com/23147878/91324376-953c1280-e7f4-11ea-8b29-ecef9526d892.png)

**Comment by slzKud** [comment]
Sorry.it has a problem.
if the dll path include wide-char,the program cannot process and show error 2. 
Like this 
![图片](https://user-images.githubusercontent.com/23147878/91324376-953c1280-e7f4-11ea-8b29-ecef9526d892.png)

**Comment by slzKud** [comment]
I think it probably raise error when loading 7z.dll. It can use LoadLibrayW to replace LoadLibraryA and use GetModuleFileNameW to replace GetModuleFileNameA. This is my suggestion.

**Comment by Wilenty** [comment]
OK, I will check and let you know. It may take a while also...

**Comment by Wilenty** [comment]
Please check it now, and let me know.

If everything is OK, I made final release of it.

**Comment by slzKud** [comment]
OK, i test it.It seems solved.
![图片](https://user-images.githubusercontent.com/23147878/91424814-df70d280-e88c-11ea-9d2b-b5cf40a32c27.png)

**Comment by slzKud** [comment]
I test the dll. And it works perfectly.it solved finally. Thank You  and Your project!!
You can make the release, it is ok.
